# Determines the number of times a k-mer pattern appears in a substring of text.

text="GCTCGACGGCTCGACCACGCGGCTCGACGCTCGACATTTAAGCTCGACTTGCTCGACAGCTCGACGCTCGACGGCTCGACGCTCGACCAGCTCGACCGAAGCTCGACGCTCGACTAGGCTCGACGCGCTCGACAGGCTCGACCGCTCGACAGGCTCGACGCTCGACGGCTCGACGGCTCGACCAGCTCGACTCGCTCGACTCAGAGGCTCGACGGCTCGACTCGCTCGACGCTCGACTTTGCTGCTCGACATGATTCTCTCGCTCGACCAATCGCTCGACTAGCCGCTCGACAATCCGGCTCGACGCTCGACTTGCTCGACCGCTCGACAAACTGGCTCGACGCTCGACGCTCGACCCGGTCGGCAGCTCGACGTGGGGCGCTCGACACGCTCGACGCTCGACAAGGCTCGACGGCTCGACTAATATAAGCTCGACAGACTGCTCGACGGTGTGGGTGGCGCTCGACGCTCGACGGTCGCTCGACTTGTGCTCGACAACGCTCGACGCTCGACGCTCGACAGCTCGACTGATAAGCTGGCTAGCTCGACGTCGCTCGACAGCTCGACGCTCGACGGCTCGACATTCCACAGCGCTCGACGTCGCTCGACCCAAACGCTCGACTGATATGCTCGACTCGCTCGACAGGCTCGACTGATGAGTCGCTCGACGAACGCTCGACGAATAACGGCTCGACTGCTCGACTTCCTCGCTCGACTGCTCGACGCTCGACCATAATGAGCTCGACGCTCGACCAAAGGGCTCGACGCTCGACTAGCTCGACGGCTCGACAGATGCTCGACGCTCGACGGTTGGCTCGACTCCTGCTGCTCGACGCTCGACCACGCTCGACCTGAAAGCTCGACTGCTCGACGCTCGACAGGCTCGACGCTCGGAGGGCTCGACGCTCGACAGCTCGACCCGCTCGACTGTGCTCGACGGCTCGACAGCTCGACCTACTGGCTCGACGCTCGACGGCAGCCGGAAGTGCTCGACAGGCTCGACGCTCGAC"
pattern = "GCTCGACGC"

def hasPattern(element, elementIndex):
    nextNElements = "";
    for i in range(0, len(pattern)):
        if i + elementIndex  < len(text):
            nextNElements += text[i + elementIndex]

    return nextNElements == pattern


def getCount():
    total = 0
    for i in range(0, len(text)):
        if hasPattern(text[i], i):
            total = total + 1
    print(total)

getCount()
